#ifndef __DEFINES_H__
#define __DEFINES_H__

#define TITLE_LABEL_FONT_SIZE 52
#define TITLE_LABEL_FONT_PATH "fonts/Marker Felt.ttf"
#define COVER_IMG_PATH "newCover.png"

#define TIMER_LABEL_FONT_SIZE 32

#define COUNT_CATS_TO_LAYER 40
#define SCALE_CAT_SPRITE 0.5f
#define SCALE_BALLOON_SPRITE 0.5f

#define RANDOM_DELAY_TIME_SEQUENCE 40
#define DURATION_GAME_OBJ_ACTION 5

#define COUNT_SPRITE_FILE_CAT 4
#define COUNT_SPRITE_FILE_BALLOON 6

#define FORMAT_SPRITE_FILE "png"

#define FILE_NAME_SPRITE_FILE_BALLOON "model/balloon0"
#define FILE_NAME_SPRITE_FILE_CAT "model/cat0"

#define DURATION_TIME_ONE_LAYER 40.0f

#endif // __DEFINES_H__
